---
title: "Simple document"
output: github_document
---

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

## Import some data

I want to import `FAS_litters.csv`.

```{r}

litters_df = read_csv("./data/FAS_litters.csv")
```
Now I want better names.

```{r}
names(litters_df)

litters_df = janitor::clean_names(litters_df)
```

Let's look at the dataset.

```{r}
litters_df

head(litters_df)
tail(litters_df)
```
One I use a lot is

```{r, eval=FALSE}
view(litters_df)
```
Here's `skimer`
```{r}
skimr::skim(litters_df)
```

## Arguments in `read_csv`

```{r}
litters_df
  read_csv(
    "data/FAS_litters.csv",
    skip = 5,
    col_names = FALSE,
    na = "Low8")
  
```
## Parsing Columns

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
tail(litters_data)
```

## Reading from excel

Reading MLB data.

```{r}
mlb11_df = read_excel("data/mlb11.xlsx")
```
LotR Words is next.

```{r}
fellow_df = read_excel("data/LotR_Words.xlsx", range = "B3:D6")
```
## Reading SAS file
```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
```


